<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Domain</AssemblyName>
    <Deterministic>true</Deterministic>
    <OutputType>Library</OutputType>
    <RootNamespace>Bookstore.Domain</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.400.63" />
  </ItemGroup>
</Project>